"use client";
import { useEffect, useMemo, useState } from "react";
import { CarFront, CircleDollarSign, LoaderCircle, Plus, Trash2 } from "lucide-react";

type MenuItem = { text: string; value: string };
type Vehicle = { id: string; year: number; make: string; model: string; trim: string; engine: string; cylinders: number | null; displacementLiters: number | null; transmission: string; drive: string; fuelType: string; cityMpg: number | null; highwayMpg: number | null; combinedMpg: number | null; annualFuelCost: number; barrelsPerYear: number | null; co2GramsPerMile: number | null; vehicleClass: string; electricRange: number | null; phevRange: number | null; maintenanceBudget?: number; insuranceBudget?: number; registrationBudget?: number };
const years = Array.from({ length: new Date().getFullYear() - 1983 }, (_, index) => String(new Date().getFullYear() + 1 - index));
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);

export function VehicleAssetManager() {
  const [assets, setAssets] = useState<Vehicle[]>([]), [year, setYear] = useState(""), [make, setMake] = useState(""), [model, setModel] = useState(""), [option, setOption] = useState("");
  const [makes, setMakes] = useState<MenuItem[]>([]), [models, setModels] = useState<MenuItem[]>([]), [options, setOptions] = useState<MenuItem[]>([]), [preview, setPreview] = useState<Vehicle | null>(null), [loading, setLoading] = useState(false);
  const [maintenance, setMaintenance] = useState(1200), [insurance, setInsurance] = useState(1800), [registration, setRegistration] = useState(250);
  useEffect(() => { try { setAssets(JSON.parse(localStorage.getItem("blended-basecamp-vehicles") ?? "[]")); } catch { localStorage.removeItem("blended-basecamp-vehicles"); } }, []);
  const load = async (action: string, query: Record<string, string>) => { const params = new URLSearchParams({ action, ...query }); const response = await fetch(`/api/vehicle-data?${params}`); if (!response.ok) throw new Error(); return response.json() as Promise<{ results?: MenuItem[]; vehicle?: Vehicle }>; };
  useEffect(() => { if (!year) return; setMake(""); setModel(""); setOption(""); setPreview(null); setLoading(true); load("makes", { year }).then((data) => setMakes(data.results ?? [])).catch(() => setMakes([])).finally(() => setLoading(false)); }, [year]);
  useEffect(() => { if (!year || !make) return; setModel(""); setOption(""); setPreview(null); setLoading(true); load("models", { year, make }).then((data) => setModels(data.results ?? [])).catch(() => setModels([])).finally(() => setLoading(false)); }, [make, year]);
  useEffect(() => { if (!year || !make || !model) return; setOption(""); setPreview(null); setLoading(true); load("options", { year, make, model }).then((data) => setOptions(data.results ?? [])).catch(() => setOptions([])).finally(() => setLoading(false)); }, [make, model, year]);
  useEffect(() => { if (!option) return; setLoading(true); load("details", { id: option }).then((data) => setPreview(data.vehicle ?? null)).catch(() => setPreview(null)).finally(() => setLoading(false)); }, [option]);
  const save = () => { if (!preview) return; const asset = { ...preview, maintenanceBudget: maintenance, insuranceBudget: insurance, registrationBudget: registration }; const next = [...assets.filter((item) => item.id !== asset.id), asset]; setAssets(next); localStorage.setItem("blended-basecamp-vehicles", JSON.stringify(next)); const raw = JSON.parse(localStorage.getItem("blended-basecamp-finance") ?? "{}"); const budget = { vehicleId: asset.id, name: `${asset.year} ${asset.make} ${asset.model}`, fuel: asset.annualFuelCost, maintenance, insurance, registration }; localStorage.setItem("blended-basecamp-finance", JSON.stringify({ ...raw, vehicleBudgets: [...(raw.vehicleBudgets ?? []).filter((item: { vehicleId: string }) => item.vehicleId !== asset.id), budget] })); };
  const total = (vehicle: Vehicle) => vehicle.annualFuelCost + (vehicle.maintenanceBudget ?? 0) + (vehicle.insuranceBudget ?? 0) + (vehicle.registrationBudget ?? 0);
  return <section className="mb-5 rounded-[26px] border border-[#527568]/25 bg-[#e8efe8] p-5 sm:p-6">
    <div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Vehicle asset garage</p><h3 className="basecamp-serif text-2xl font-bold">Add a vehicle by exact configuration.</h3><p className="mt-1 text-xs text-[#68746f]">Choose it like an auto-parts site. Basecamp loads known government vehicle specifications and starts its annual budget.</p></div><CarFront className="shrink-0 text-[#527568]" /></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <Select label="Year" value={year} set={setYear} options={years.map((value) => ({ text: value, value }))} />
      <Select label="Make" value={make} set={setMake} options={makes} disabled={!year} />
      <Select label="Model" value={model} set={setModel} options={models} disabled={!make} />
      <Select label="Engine / configuration" value={option} set={setOption} options={options} disabled={!model} />
    </div>
    {loading ? <p className="mt-4 flex items-center gap-2 text-xs font-bold text-[#527568]"><LoaderCircle className="size-4 animate-spin" /> Loading vehicle data…</p> : null}
    {preview ? <div className="mt-5 rounded-2xl bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{preview.year} {preview.make} {preview.model}</p><p className="text-xs text-[#68746f]">{preview.engine} · {preview.transmission} · {preview.drive}</p></div><span className="rounded-full bg-[#e2eee7] px-3 py-1 text-xs font-bold">{preview.combinedMpg ? `${preview.combinedMpg} MPG combined` : preview.fuelType}</span></div>
      <div className="mt-4 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><Spec label="Class" value={preview.vehicleClass}/><Spec label="Fuel" value={preview.fuelType}/><Spec label="City / highway" value={`${preview.cityMpg ?? "—"} / ${preview.highwayMpg ?? "—"} MPG`}/><Spec label="Factory fuel estimate" value={`${money(preview.annualFuelCost)}/year`}/></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-3"><Budget label="Maintenance / year" value={maintenance} set={setMaintenance}/><Budget label="Insurance / year" value={insurance} set={setInsurance}/><Budget label="Registration / year" value={registration} set={setRegistration}/></div>
      <button className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#244a40] px-4 py-3 text-sm font-bold text-white" onClick={save}><Plus size={17}/> Add managed vehicle</button>
    </div> : null}
    {assets.length ? <div className="mt-5 grid gap-3 lg:grid-cols-2">{assets.map((asset) => <article className="rounded-2xl bg-[#203f37] p-4 text-white" key={asset.id}><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-white/10"><CarFront size={20}/></span><div className="min-w-0 flex-1"><b>{asset.year} {asset.make} {asset.model}</b><p className="truncate text-xs text-white/60">{asset.engine} · {asset.fuelType}</p></div><button aria-label="Delete vehicle" onClick={() => { const next = assets.filter((item) => item.id !== asset.id); setAssets(next); localStorage.setItem("blended-basecamp-vehicles", JSON.stringify(next)); const raw = JSON.parse(localStorage.getItem("blended-basecamp-finance") ?? "{}"); localStorage.setItem("blended-basecamp-finance", JSON.stringify({ ...raw, vehicleBudgets: (raw.vehicleBudgets ?? []).filter((item: { vehicleId: string }) => item.vehicleId !== asset.id) })); }}><Trash2 size={16}/></button></div><div className="mt-4 flex items-center justify-between rounded-xl bg-white/10 p-3"><span className="flex items-center gap-2 text-xs"><CircleDollarSign size={15}/> Planned annual ownership</span><b>{money(total(asset))}</b></div></article>)}</div> : null}
  </section>;
}
function Select({ label, value, set, options, disabled }: { label: string; value: string; set: (value: string) => void; options: MenuItem[]; disabled?: boolean }) { return <label className="text-[10px] font-extrabold uppercase tracking-wider">{label}<select className="mt-2 w-full rounded-xl border border-black/10 bg-white px-3 py-3 text-sm disabled:opacity-50" disabled={disabled} value={value} onChange={(event) => set(event.target.value)}><option value="">Select {label.toLowerCase()}</option>{options.map((item) => <option key={item.value} value={item.value}>{item.text}</option>)}</select></label>; }
function Spec({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-[#f4f1e9] p-3"><span className="block text-[9px] font-bold uppercase text-[#78827e]">{label}</span><b className="mt-1 block">{value}</b></div>; }
function Budget({ label, value, set }: { label: string; value: number; set: (value: number) => void }) { return <label className="text-[10px] font-extrabold uppercase tracking-wider">{label}<input className="mt-2 w-full rounded-xl border border-black/10 px-3 py-3 text-sm" min="0" type="number" value={value} onChange={(event) => set(Number(event.target.value))}/></label>; }
