"use client";

import { useEffect, useMemo, useState } from "react";
import { BookOpen, CalendarDays, Check, ChevronLeft, ChevronRight, CirclePlus, HeartHandshake, Home, Leaf, Sparkles, Target, Users } from "lucide-react";

type PlannerEvent = { id:number; day:number; title:string; category:Category };
type Entry = { id:number; title:string; body:string; intention:string };
type Category = keyof typeof categories;
const categories = { faith:{label:"Faith",color:"#d28b46"}, family:{label:"Family",color:"#b85e65"}, work:{label:"Work",color:"#567e72"}, mission:{label:"Mission",color:"#5c6d98"}, future:{label:"Our Future",color:"#827051"} };
const samples:PlannerEvent[] = [{id:1,day:26,title:"Weekly devotion",category:"faith"},{id:2,day:27,title:"Family check-in",category:"family"},{id:3,day:28,title:"Blended Works planning",category:"work"},{id:4,day:29,title:"Serve together",category:"mission"}];
const months=["January","February","March","April","May","June","July","August","September","October","November","December"];

export default function PlannerPage(){
  const today=new Date();
  const [view,setView]=useState(new Date(today.getFullYear(),today.getMonth(),1));
  const [day,setDay]=useState(today.getDate()); const [events,setEvents]=useState<PlannerEvent[]>(samples);
  const [eventTitle,setEventTitle]=useState(""); const [category,setCategory]=useState<Category>("family");
  const [title,setTitle]=useState(""); const [body,setBody]=useState(""); const [intention,setIntention]=useState(""); const [entries,setEntries]=useState<Entry[]>([]); const [saved,setSaved]=useState(false); const [mobileView,setMobileView]=useState<"calendar"|"journal">("calendar");
  useEffect(()=>{try{const stored=localStorage.getItem("blended-planner");if(stored){const data=JSON.parse(stored) as {events?:PlannerEvent[];entries?:Entry[]};if(data.events)setEvents(data.events);if(data.entries)setEntries(data.entries)}}catch{localStorage.removeItem("blended-planner")}},[]);
  useEffect(()=>{localStorage.setItem("blended-planner",JSON.stringify({events,entries}))},[events,entries]);
  const days=useMemo(()=>{const y=view.getFullYear(),m=view.getMonth();return [...Array(new Date(y,m,1).getDay()).fill(null),...Array.from({length:new Date(y,m+1,0).getDate()},(_,i)=>i+1)] as (number|null)[]},[view]);
  const addEvent=()=>{if(!eventTitle.trim())return;setEvents([...events,{id:Date.now(),day,title:eventTitle.trim(),category}]);setEventTitle("")};
  const saveEntry=()=>{if(!body.trim()&&!intention.trim())return;setEntries([{id:Date.now(),title:title||"Daily reflection",body,intention},...entries]);setTitle("");setBody("");setIntention("");setSaved(true);setTimeout(()=>setSaved(false),1800)};
  const input="w-full rounded-xl border border-white/20 bg-white/10 px-3 py-2.5 text-sm text-white outline-none placeholder:text-white/45 focus:border-[#e8d39f]";
  return <main className="min-h-screen">
    <header className="border-b border-[var(--line)] bg-[#fbf8f1]/90 px-4 py-4 backdrop-blur md:px-8"><div className="mx-auto flex max-w-[1500px] items-center justify-between"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-[var(--forest)] text-[#f8ecd1]"><Leaf size={20}/></div><div><p className="planner-serif text-xl font-bold leading-none">The Blended Planner</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.22em] text-[#7a6a50]">by Blended Works</p></div></div><div className="hidden items-center gap-2 text-sm text-[#5d6e68] sm:flex"><HeartHandshake size={17}/>Plan with purpose. Grow together.</div></div></header>
    <div className="mx-auto grid max-w-[1500px] md:grid-cols-[220px_1fr]">
      <aside className="hidden min-h-[calc(100vh-73px)] border-r border-[var(--line)] bg-[#eee8dc] p-5 md:block"><p className="mb-4 px-3 text-xs font-bold uppercase tracking-[.18em] text-[#8b7a5c]">Your rhythm</p><nav className="space-y-1 text-sm font-medium"><a href="#today" className="flex items-center gap-3 rounded-xl bg-[var(--forest)] px-3 py-3 text-white"><Home size={18}/>Today</a><a href="#calendar" className="flex items-center gap-3 rounded-xl px-3 py-3 hover:bg-white/60"><CalendarDays size={18}/>Calendar</a><a href="#journal" className="flex items-center gap-3 rounded-xl px-3 py-3 hover:bg-white/60"><BookOpen size={18}/>Planning journal</a></nav><div className="mt-10 rounded-2xl border border-[#cdbf9e] bg-[#f8f2e4] p-4"><Sparkles className="mb-3 text-[#b7793f]" size={20}/><p className="planner-serif text-lg font-bold">This week’s focus</p><p className="mt-2 text-sm leading-6 text-[#607069]">Make room for what matters, then take the next faithful step.</p></div></aside>
      <section id="today" className="min-w-0 p-4 sm:p-6 lg:p-9"><div className="mb-7 flex flex-col justify-between gap-3 lg:flex-row lg:items-end"><div><p className="mb-1 text-sm font-semibold text-[#a36b3c]">{today.toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"})}</p><h1 className="planner-serif text-4xl font-bold tracking-tight sm:text-5xl">Let’s shape the days ahead.</h1></div><div className="flex flex-wrap gap-2">{Object.entries(categories).map(([key,item])=><span key={key} className="flex items-center gap-2 rounded-full bg-white/70 px-3 py-1.5 text-xs font-semibold"><i className="size-2 rounded-full" style={{background:item.color}}/>{item.label}</span>)}</div></div>
        <div className="mb-5 grid h-12 grid-cols-2 rounded-2xl bg-[#ded6c7] p-1 md:hidden"><button className={`rounded-xl text-sm font-semibold ${mobileView==="calendar"?"bg-white shadow-sm":""}`} onClick={()=>setMobileView("calendar")}>Calendar</button><button className={`rounded-xl text-sm font-semibold ${mobileView==="journal"?"bg-white shadow-sm":""}`} onClick={()=>setMobileView("journal")}>Journal</button></div>
        <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(340px,.7fr)]">
          <section id="calendar" className={`${mobileView==="calendar"?"block":"hidden"} overflow-hidden rounded-[26px] border border-[var(--line)] bg-[var(--cream)] shadow-[0_18px_50px_rgba(54,66,56,.08)] xl:block`}><div className="flex items-center justify-between border-b border-[var(--line)] p-5 sm:p-6"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#8c7c61]">Monthly view</p><h2 className="planner-serif text-3xl font-bold">{months[view.getMonth()]} {view.getFullYear()}</h2></div><div className="flex gap-2"><button aria-label="Previous month" onClick={()=>setView(new Date(view.getFullYear(),view.getMonth()-1,1))} className="grid size-10 place-items-center rounded-xl border bg-white"><ChevronLeft/></button><button aria-label="Next month" onClick={()=>setView(new Date(view.getFullYear(),view.getMonth()+1,1))} className="grid size-10 place-items-center rounded-xl border bg-white"><ChevronRight/></button></div></div>
            <div className="grid grid-cols-7 border-b border-[var(--line)] bg-[#f3eee4] text-center text-[10px] font-bold uppercase tracking-wider text-[#7c725f] sm:text-xs">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><div className="py-3" key={d}>{d}</div>)}</div><div className="grid grid-cols-7">{days.map((d,i)=><button key={i} disabled={!d} onClick={()=>d&&setDay(d)} className={`min-h-[76px] border-b border-r border-[var(--line)] p-1.5 text-left transition sm:min-h-[108px] sm:p-2 ${d===day?"bg-[#eef3ed] ring-2 ring-inset ring-[#567e72]":"hover:bg-[#faf6ed]"}`}>{d&&<><span className={`inline-grid size-6 place-items-center rounded-full text-xs font-semibold sm:size-7 sm:text-sm ${d===today.getDate()&&view.getMonth()===today.getMonth()?"bg-[var(--forest)] text-white":""}`}>{d}</span><div className="mt-1 space-y-1">{events.filter(e=>e.day===d).slice(0,2).map(e=><div key={e.id} className="truncate rounded px-1.5 py-1 text-[9px] font-semibold text-white sm:text-[11px]" style={{background:categories[e.category].color}}>{e.title}</div>)}</div></>}</button>)}</div>
            <div className="border-t border-[var(--line)] bg-[#faf6ee] p-4 sm:p-5"><p className="mb-3 text-sm font-bold">Add to {months[view.getMonth()]} {day}</p><div className="flex flex-col gap-2 sm:flex-row"><input value={eventTitle} onChange={e=>setEventTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addEvent()} placeholder="What are you planning?" className="h-10 flex-1 rounded-lg border bg-white px-3 text-sm outline-[#567e72]"/><select value={category} onChange={e=>setCategory(e.target.value as Category)} className="h-10 rounded-lg border bg-white px-3 text-sm">{Object.entries(categories).map(([key,v])=><option key={key} value={key}>{v.label}</option>)}</select><button onClick={addEvent} className="flex h-10 items-center justify-center gap-2 rounded-lg bg-[var(--forest)] px-4 text-sm font-semibold text-white"><CirclePlus size={18}/>Add</button></div></div>
          </section>
          <section id="journal" className={`${mobileView==="journal"?"block":"hidden"} xl:block`}><div className="rounded-[26px] bg-[var(--forest)] p-6 text-white shadow-[0_18px_50px_rgba(54,66,56,.13)] sm:p-7"><div className="mb-6 flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d9c79f]">Planning journal</p><h2 className="planner-serif mt-1 text-3xl font-bold">Pause. Listen. Plan.</h2></div><BookOpen className="text-[#e6c98c]"/></div><label className="text-xs font-bold uppercase tracking-wider text-[#d8d8ca]">Today, I’m grateful for...</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Give this reflection a title" className={`${input} mt-2`}/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Notice the good, name what is difficult, and make space for grace..." className={`${input} mt-3 min-h-32 resize-y`}/><label className="mt-5 block text-xs font-bold uppercase tracking-wider text-[#d8d8ca]">One faithful next step</label><textarea value={intention} onChange={e=>setIntention(e.target.value)} placeholder="What can you do today—with what you have?" className={`${input} mt-2 min-h-24 resize-y`}/><button onClick={saveEntry} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#e8d39f] px-4 py-3 text-sm font-bold text-[#29483e]">{saved?<><Check size={18}/>Saved on this device</>:<><BookOpen size={18}/>Save reflection</>}</button></div>
            <div className="mt-5 grid grid-cols-3 gap-3">{[{icon:Users,n:"Together",t:"People"},{icon:Target,n:"Forward",t:"Purpose"},{icon:Leaf,n:"Grounded",t:"Faith"}].map(({icon:Icon,n,t})=><div key={n} className="rounded-2xl border border-[var(--line)] bg-white/65 p-3 text-center"><Icon className="mx-auto mb-2 text-[#9a6d43]" size={19}/><p className="text-xs font-bold">{n}</p><p className="text-[10px] text-[#728079]">{t}</p></div>)}</div>{entries.length>0&&<div className="mt-5 rounded-2xl border border-[var(--line)] bg-white/70 p-5"><p className="mb-3 text-xs font-bold uppercase tracking-wider text-[#8c7c61]">Recent reflections</p>{entries.slice(0,3).map(e=><article className="border-t border-[var(--line)] py-3 first:border-0" key={e.id}><p className="planner-serif font-bold">{e.title}</p><p className="mt-1 line-clamp-2 text-sm text-[#66736e]">{e.body||e.intention}</p></article>)}</div>}</section>
        </div><footer className="mt-8 flex flex-col justify-between gap-2 border-t border-[var(--line)] pt-5 text-xs text-[#78837e] sm:flex-row"><p>Built for real life, shared purpose, and new beginnings.</p><p>Your entries stay on this device in this free first edition.</p></footer>
      </section>
    </div>
  </main>
}
