import { defineField, defineType } from "sanity";

export const basecampTripType = defineType({
  name: "basecampTrip",
  title: "Basecamp trip",
  type: "document",
  fields: [
    defineField({ name: "ownerId", title: "Owner ID", type: "string", readOnly: true, hidden: true }),
    defineField({ name: "localId", title: "Trip ID", type: "number", readOnly: true }),
    defineField({ name: "archived", title: "Archived", type: "boolean", initialValue: false }),
    defineField({ name: "archivedAt", title: "Archived at", type: "datetime", readOnly: true }),
    defineField({ name: "origin", title: "Starting location", type: "string" }),
    defineField({ name: "originLatitude", title: "Origin latitude", type: "number", hidden: true }),
    defineField({ name: "originLongitude", title: "Origin longitude", type: "number", hidden: true }),
    defineField({ name: "destination", title: "Destination", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "destinationLatitude", title: "Destination latitude", type: "number", hidden: true }),
    defineField({ name: "destinationLongitude", title: "Destination longitude", type: "number", hidden: true }),
    defineField({ name: "property", title: "Property or campground", type: "string" }),
    defineField({ name: "stayType", title: "Stay type", type: "string", options: { list: ["campsite", "hotel", "rental", "boondocking"] } }),
    defineField({ name: "arrival", title: "Arrival", type: "date" }),
    defineField({ name: "arrivalTime", title: "Arrival time", type: "string" }),
    defineField({ name: "departure", title: "Departure", type: "date" }),
    defineField({ name: "departureTime", title: "Departure time", type: "string" }),
    defineField({ name: "timeZoneOffsetMinutes", title: "Timezone offset", type: "number", hidden: true }),
    defineField({ name: "confirmation", title: "Confirmation", type: "string" }),
    defineField({ name: "cost", title: "Estimated total", type: "string" }),
    defineField({ name: "notes", title: "Notes", type: "text" }),
    defineField({ name: "reserved", title: "Reservation confirmed", type: "boolean" }),
    defineField({ name: "travelMode", title: "Travel mode", type: "string" }),
    defineField({ name: "vehicleId", title: "Vehicle ID", type: "string" }),
    defineField({ name: "fuelPrice", title: "Fuel price", type: "number" }),
    defineField({ name: "customMpg", title: "Custom MPG", type: "number" }),
    defineField({ name: "otherTravelCost", title: "Other travel cost", type: "number" }),
    defineField({ name: "estimatedMiles", title: "Estimated miles", type: "number" }),
    defineField({ name: "estimatedFuelCost", title: "Estimated fuel cost", type: "number" }),
    defineField({ name: "estimatedMaintenance", title: "Estimated maintenance", type: "number" }),
    defineField({ name: "estimatedOwnership", title: "Estimated ownership", type: "number" }),
    defineField({ name: "estimatedTravelTotal", title: "Estimated travel total", type: "number" }),
    defineField({ name: "readinessDone", title: "Readiness checklist", type: "object", fields: [
      defineField({ name: "confirmHours", title: "Confirm hours", type: "boolean" }),
      defineField({ name: "internetBackup", title: "Internet backup", type: "boolean" }),
      defineField({ name: "utilities", title: "Utilities", type: "boolean" }),
      defineField({ name: "weatherRoads", title: "Weather and roads", type: "boolean" }),
    ] }),
  ],
  preview: {
    select: { destination: "destination", property: "property", arrival: "arrival" },
    prepare: ({ destination, property, arrival }) => ({
      title: property || destination || "Untitled trip",
      subtitle: [destination, arrival].filter(Boolean).join(" · "),
    }),
  },
});
