import { defineField, defineType } from "sanity";

export const siteSettingsType = defineType({
  name: "siteSettings",
  title: "Homepage Settings",
  type: "document",
  fields: [
    defineField({
      name: "heroEyebrow",
      title: "Hero eyebrow",
      type: "string",
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: "heroHeadline",
      title: "Hero headline",
      type: "string",
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: "heroAccent",
      title: "Hero accent line",
      type: "string",
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: "heroIntroduction",
      title: "Hero introduction",
      type: "text",
      rows: 4,
      validation: (rule) => rule.required().max(320),
    }),
    defineField({
      name: "aboutHeadline",
      title: "About headline",
      type: "text",
      rows: 3,
      validation: (rule) => rule.required().max(240),
    }),
    defineField({
      name: "aboutRobinAndLaura",
      title: "About Robin and Laura",
      type: "text",
      rows: 5,
      validation: (rule) => rule.required().max(600),
    }),
    defineField({
      name: "aboutJournal",
      title: "About the journal",
      type: "text",
      rows: 5,
      validation: (rule) => rule.required().max(600),
    }),
    defineField({
      name: "aboutPageEyebrow",
      title: "About page eyebrow",
      type: "string",
      validation: (rule) => rule.required().max(100),
    }),
    defineField({
      name: "aboutPageHeadline",
      title: "About page headline",
      type: "text",
      rows: 3,
      validation: (rule) => rule.required().max(240),
    }),
    defineField({
      name: "aboutPageIntroduction",
      title: "About page introduction",
      type: "text",
      rows: 4,
      validation: (rule) => rule.required().max(500),
    }),
    defineField({
      name: "robinHeadline",
      title: "Robin headline",
      type: "string",
      validation: (rule) => rule.required().max(120),
    }),
    defineField({
      name: "robinBio",
      title: "Robin biography",
      type: "text",
      rows: 12,
      validation: (rule) => rule.required().max(2400),
    }),
    defineField({
      name: "lauraHeadline",
      title: "Laura headline",
      type: "string",
      validation: (rule) => rule.required().max(120),
    }),
    defineField({
      name: "lauraBio",
      title: "Laura biography",
      type: "text",
      rows: 12,
      validation: (rule) => rule.required().max(2400),
    }),
    defineField({
      name: "storyHeadline",
      title: "Shared story headline",
      type: "string",
      validation: (rule) => rule.required().max(160),
    }),
    defineField({
      name: "storyBody",
      title: "Shared story",
      type: "text",
      rows: 12,
      validation: (rule) => rule.required().max(3000),
    }),
    defineField({
      name: "valuesHeadline",
      title: "Values headline",
      type: "string",
      validation: (rule) => rule.required().max(180),
    }),
    defineField({
      name: "trustPromise",
      title: "Trust promise",
      type: "text",
      rows: 6,
      validation: (rule) => rule.required().max(1000),
    }),
    defineField({
      name: "servicesHeadline",
      title: "Services headline",
      type: "string",
      validation: (rule) => rule.required().max(160),
    }),
    defineField({
      name: "servicesIntroduction",
      title: "Services introduction",
      type: "text",
      rows: 5,
      validation: (rule) => rule.required().max(700),
    }),
  ],
  preview: {
    prepare: () => ({
      title: "Homepage Settings",
      subtitle: "Editable homepage copy",
    }),
  },
});
